name: build-and-test-2.13

on:
  push:
  pull_request:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode
  MAVEN_TEST_OPTS: -Dtest.fork.count=1

jobs:
  build-scala:
    runs-on: ubuntu-latest
    # avoid duplicate jobs on PRs from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
=======
<<<<<<< HEAD
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
=======
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
>>>>>>> 2219fefbbf (Update github actions to latest versions)
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
<<<<<<< HEAD
<<<<<<< HEAD
      - name: Set Scala version
        run: ./build/change-scala-version.sh 2.13
      - name: Build with Maven
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Unit tests
        id: test
<<<<<<< HEAD
=======
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
=======
      - name: Build with Maven
        run: mvn clean install -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
=======
>>>>>>> 354f512a3f (Fix duplicate CI build)
      - name: Set Scala version
        run: ./build/change-scala-version.sh 2.13
      - name: Build with Maven
        run: ./build/mvn clean install -B -DskipTests -T4 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      - name: Unit tests
        id: test
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
        continue-on-error: true
        run: |
          set -o pipefail
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry
        if: steps.test.outcome=='failure'
<<<<<<< HEAD
        continue-on-error: true
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry-retry
        if: steps.test-retry.outcome=='failure'
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM | tee -a test.log
=======
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
        continue-on-error: true
      - name: HBase 1.4 unit tests (retry)
        id: hbase-test-retry
        if: steps.hbase-test.outcome=='failure'
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
      - name: Integration Tests
        run: mvn failsafe:integration-test failsafe:verify $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
      - name: Remove geomesa artifacts
<<<<<<< HEAD
        if: success() || failure()
=======
>>>>>>> 2219fefbbf (Update github actions to latest versions)
        run: rm -rf ~/.m2/repository/org/locationtech/geomesa
