name: build-and-test-2.13

on:
  push:
  pull_request:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 1ea467d89c (Pin github actions to specific hash and make them read-only)
=======
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode
  MAVEN_TEST_OPTS: -Dtest.fork.count=1

=======
>>>>>>> 3f7d76fd96 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
<<<<<<< HEAD
=======
env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false --batch-mode
  MAVEN_TEST_OPTS: -Dtest.fork.count=1

>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
=======
>>>>>>> 1ea467d89c (Pin github actions to specific hash and make them read-only)
=======
=======
env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false --batch-mode
  MAVEN_TEST_OPTS: -o -Dtest.fork.count=1

>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
jobs:
  build-scala:
    runs-on: ubuntu-latest
    # avoid duplicate jobs on PRs from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
=======
=======
>>>>>>> 7b142c7b6b6 (Pin github actions to specific hash and make them read-only)
=======
>>>>>>> efd0e3b5df5 (Update github actions to latest versions)
=======
>>>>>>> 4dabc7090ee (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
=======
=======
>>>>>>> 1ab72975848 (Pin github actions to specific hash and make them read-only)
=======
>>>>>>> b2d0909c502 (Update github actions to latest versions)
=======
>>>>>>> ab48b6cc8bf (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
=======
=======
>>>>>>> 7ebd6cf4994 (Pin github actions to specific hash and make them read-only)
=======
>>>>>>> 3b0999a6fa3 (Update github actions to latest versions)
=======
>>>>>>> bd17d0dcaf4 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
>>>>>>> e4d07a827c5 (Update github actions to latest versions)
>>>>>>> e1c3d741df7 (Update github actions to latest versions)
>>>>>>> 2e4ce461484 (Update github actions to latest versions)
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
=======
=======
>>>>>>> ff29f098393 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
>>>>>>> 8873778c15c (Update github actions to latest versions)
=======
<<<<<<< HEAD
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
=======
>>>>>>> 1ea467d89c (Pin github actions to specific hash and make them read-only)
>>>>>>> db0ba5df73f (Pin github actions to specific hash and make them read-only)
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
=======
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
>>>>>>> 2219fefbbf (Update github actions to latest versions)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
=======
=======
>>>>>>> 8873778c15c (Update github actions to latest versions)
=======
=======
>>>>>>> 1ea467d89c (Pin github actions to specific hash and make them read-only)
>>>>>>> db0ba5df73f (Pin github actions to specific hash and make them read-only)
=======
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
>>>>>>> 3f7d76fd96 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> ff29f098393 (Pin github actions to specific hash and make them read-only)
=======
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
>>>>>>> 8873778c15c (Update github actions to latest versions)
=======
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
=======
>>>>>>> 1ea467d89c (Pin github actions to specific hash and make them read-only)
>>>>>>> db0ba5df73f (Pin github actions to specific hash and make them read-only)
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
=======
>>>>>>> da5f8fa1a3 (Fix duplicate CI build)
      - name: Set Scala version
        run: ./build/change-scala-version.sh 2.13
      - name: Build with Maven
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Unit tests
        id: test
<<<<<<< HEAD
=======
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - name: Build with Maven
        run: mvn clean install -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
=======
>>>>>>> 354f512a3f (Fix duplicate CI build)
      - name: Set Scala version
        run: ./build/change-scala-version.sh 2.13
      - name: Build with Maven
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Unit tests
        id: test
<<<<<<< HEAD
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
=======
=======
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
<<<<<<< HEAD
>>>>>>> 7b87d0240e7 (Add Eclipse license scanning to CI (#2949))
<<<<<<< HEAD
>>>>>>> a1f8f8a1f9c (Add Eclipse license scanning to CI (#2949))
=======
=======
=======
>>>>>>> 27d2a13b23 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
<<<<<<< HEAD
>>>>>>> ce69a697516 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
<<<<<<< HEAD
>>>>>>> a0805e2ff17 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
=======
=======
=======
=======
      - name: Build with Maven
        run: mvn clean install -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
=======
>>>>>>> 354f512a3f (Fix duplicate CI build)
      - name: Set Scala version
        run: ./build/change-scala-version.sh 2.13
      - name: Build with Maven
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Unit tests
        id: test
<<<<<<< HEAD
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> 9796c943ef (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> 579f9595dac (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> 8873778c15c (Update github actions to latest versions)
=======
=======
=======
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
>>>>>>> 3bd67b47128 (Add Eclipse license scanning to CI (#2949))
>>>>>>> 5949549abf8 (Add Eclipse license scanning to CI (#2949))
        continue-on-error: true
        run: |
          set -o pipefail
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry
        if: steps.test.outcome=='failure'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        continue-on-error: true
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry-retry
        if: steps.test-retry.outcome=='failure'
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM | tee -a test.log
=======
=======
>>>>>>> a1f8f8a1f9c (Add Eclipse license scanning to CI (#2949))
=======
>>>>>>> a0805e2ff17 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
=======
>>>>>>> 8873778c15c (Update github actions to latest versions)
=======
>>>>>>> 5949549abf8 (Add Eclipse license scanning to CI (#2949))
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
=======
>>>>>>> 7b87d0240e7 (Add Eclipse license scanning to CI (#2949))
=======
>>>>>>> ce69a697516 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
>>>>>>> 579f9595dac (Update github actions to latest versions)
=======
<<<<<<< HEAD
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
=======
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
>>>>>>> 3bd67b47128 (Add Eclipse license scanning to CI (#2949))
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
<<<<<<< HEAD
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
>>>>>>> 27d2a13b23 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
=======
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
        continue-on-error: true
      - name: HBase 1.4 unit tests (retry)
        id: hbase-test-retry
        if: steps.hbase-test.outcome=='failure'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
=======
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
=======
<<<<<<< HEAD
>>>>>>> 579f9595dac (Update github actions to latest versions)
      - name: Integration Tests
        run: mvn failsafe:integration-test failsafe:verify $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
      - name: Remove geomesa artifacts
<<<<<<< HEAD
        if: success() || failure()
=======
>>>>>>> 2219fefbbf (Update github actions to latest versions)
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
<<<<<<< HEAD
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
>>>>>>> 27d2a13b23 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
=======
>>>>>>> 9796c943ef (Update github actions to latest versions)
      - name: Integration Tests
        run: mvn failsafe:integration-test failsafe:verify $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
      - name: Remove geomesa artifacts
<<<<<<< HEAD
        if: success() || failure()
<<<<<<< HEAD
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
=======
=======
>>>>>>> 2219fefbbf (Update github actions to latest versions)
>>>>>>> 9796c943ef (Update github actions to latest versions)
=======
      - name: Integration Tests
        run: mvn failsafe:integration-test failsafe:verify $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
      - name: Remove geomesa artifacts
        if: success() || failure()
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
>>>>>>> ab4e4d07e5 (Add Eclipse license scanning to CI (#2949))
        run: rm -rf ~/.m2/repository/org/locationtech/geomesa
