name: build-and-test-2.12

on:
  push:
  pull_request:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

<<<<<<< HEAD
<<<<<<< HEAD
env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode
  MAVEN_TEST_OPTS: -Dtest.fork.count=1

=======
>>>>>>> 3f7d76fd96 (Pin github actions to specific hash and make them read-only)
=======
env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false --batch-mode
  MAVEN_TEST_OPTS: -Dtest.fork.count=1

>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
jobs:
  build-scala:
    runs-on: ubuntu-latest
    # avoid duplicate jobs on PRs from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
=======
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
>>>>>>> 2219fefbbf (Update github actions to latest versions)
=======
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
>>>>>>> 3f7d76fd96 (Pin github actions to specific hash and make them read-only)
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Unit tests
        id: test
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
=======
        run: mvn clean install -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      - name: Build with Maven
=======
>>>>>>> 354f512a3f (Fix duplicate CI build)
        run: ./build/mvn clean install -B -DskipTests -T4 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      - name: Unit tests
        id: test
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
=======
=======
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Unit tests
        id: test
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
<<<<<<< HEAD
>>>>>>> 7b87d0240e7 (Add Eclipse license scanning to CI (#2949))
=======
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
>>>>>>> 27d2a13b23 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
>>>>>>> ce69a697516 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
        continue-on-error: true
      - name: Unit tests (retry)
        id: test-retry
        if: steps.test.outcome=='failure'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
=======
>>>>>>> 7b87d0240e7 (Add Eclipse license scanning to CI (#2949))
=======
>>>>>>> ce69a697516 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
>>>>>>> 27d2a13b23 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
        continue-on-error: true
      - name: HBase 1.4 unit tests (retry)
        id: hbase-test-retry
        if: steps.hbase-test.outcome=='failure'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
      - name: Integration Tests
        run: mvn failsafe:integration-test failsafe:verify $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
      - name: Remove geomesa artifacts
<<<<<<< HEAD
        if: success() || failure()
=======
>>>>>>> 2219fefbbf (Update github actions to latest versions)
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
>>>>>>> 27d2a13b23 (GEOMESA-3246 Update Scala to 2.12.17 (#2976))
      - name: Integration Tests
        run: mvn failsafe:integration-test failsafe:verify $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
      - name: Remove geomesa artifacts
        if: success() || failure()
>>>>>>> 0741686e65 (Add Eclipse license scanning to CI (#2949))
        run: rm -rf ~/.m2/repository/org/locationtech/geomesa
