name: scala-2.13

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
    tags:
      - '**'
  pull_request:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

<<<<<<< HEAD
=======
<<<<<<< HEAD
env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode
  MAVEN_TEST_OPTS: -Dtest.fork.count=1

=======
>>>>>>> 3f7d76fd96 (Pin github actions to specific hash and make them read-only)
>>>>>>> 6eeeb6df9c0 (Pin github actions to specific hash and make them read-only)
jobs:
<<<<<<< HEAD
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      scala-version: "2.13"
=======
  build-scala:
    runs-on: ubuntu-latest
    # avoid duplicate jobs on PRs from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
<<<<<<< HEAD
      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
=======
=======
=======
>>>>>>> 21e676de489 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
=======
=======
>>>>>>> b64e66e7b1f (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
=======
=======
>>>>>>> 7b142c7b6b6 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
=======
=======
>>>>>>> 1ab72975848 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
=======
=======
>>>>>>> 7ebd6cf4994 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
>>>>>>> e4d07a827c5 (Update github actions to latest versions)
>>>>>>> e1c3d741df7 (Update github actions to latest versions)
>>>>>>> 2e4ce461484 (Update github actions to latest versions)
>>>>>>> 4b83fbe2bea (Update github actions to latest versions)
>>>>>>> 0061b1ce405 (Update github actions to latest versions)
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
=======
=======
>>>>>>> ff29f098393 (Pin github actions to specific hash and make them read-only)
<<<<<<< HEAD
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
=======
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
>>>>>>> 2219fefbbf (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
<<<<<<< HEAD
>>>>>>> 13e906f47ad (Update github actions to latest versions)
=======
=======
=======
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
>>>>>>> 3f7d76fd96 (Pin github actions to specific hash and make them read-only)
>>>>>>> ff29f098393 (Pin github actions to specific hash and make them read-only)
>>>>>>> 69e294d5b1a (Pin github actions to specific hash and make them read-only)
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
<<<<<<< HEAD
<<<<<<< HEAD
      - name: Set Scala version
        run: ./build/scripts/change-scala-version.sh 2.13
      - name: Build with Maven
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Unit tests
        id: test
<<<<<<< HEAD
=======
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
=======
      - name: Build with Maven
        run: mvn clean install -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
=======
>>>>>>> 354f512a3f (Fix duplicate CI build)
      - name: Set Scala version
        run: ./build/change-scala-version.sh 2.13
      - name: Build with Maven
        run: ./build/mvn clean install -B -DskipTests -T4 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      - name: Unit tests
        id: test
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
        continue-on-error: true
        run: |
          set -o pipefail
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry
        if: steps.test.outcome=='failure'
<<<<<<< HEAD
        continue-on-error: true
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry-retry
        if: steps.test-retry.outcome=='failure'
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM | tee -a test.log
=======
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
=======
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
      - name: HBase 1.4 unit tests
        id: hbase-test
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
        continue-on-error: true
      - name: HBase 1.4 unit tests (retry)
        id: hbase-test-retry
        if: steps.hbase-test.outcome=='failure'
<<<<<<< HEAD
        run: mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS -o -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1
=======
        run: mvn surefire:test -pl geomesa-hbase/geomesa-hbase-datastore -Phbase1 -o -B -Dtest.fork.count=1 -Dmaven.test.jvmargs="-Xmx4g -XX:-UseGCOverheadLimit"
>>>>>>> 2219fefbbf (Update github actions to latest versions)
>>>>>>> ce7c87cd883 (Update github actions to latest versions)
      - name: Integration Tests
        run: mvn failsafe:integration-test failsafe:verify $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS
>>>>>>> 7dc7bc5633c (Update github actions to latest versions)
      - name: Remove geomesa artifacts
<<<<<<< HEAD
        if: success() || failure()
=======
>>>>>>> 2219fefbbf (Update github actions to latest versions)
        run: rm -rf ~/.m2/repository/org/locationtech/geomesa
>>>>>>> c5242db13e4 (Update github actions to latest versions)
